modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0"

[[mods]]
modId="dalek_mod_redstone"
version="${file.jarVersion}"
displayName="Dalek Mod Redstone"
logoFile="DMR logo.png"
credits="Jayson and the DM addon creators for helping me out"
authors="Frogrilla"
description='''
Adds redstone features to Dalek Mod so that you can make interactive builds.
'''

[[dependencies.dalek_mod_redstone]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dalek_mod_redstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dalek_mod_redstone]]
    modId="dalekmod"
    mandatory=true
    versionRange="[68.0.0,)"
